routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect()->route('login');
});

Route::resource('warehouse', WarehouseController::class);
Route::resource('sellpoint', SellpointController::class);
Route::resource('article', ArticleController::class);
Route::resource('employe', EmployeController::class);
Route::resource('selling', SellingController::class);
Route::resource('messagerie', MessagerieController::class);

Route::group(['prefix' => 'selling'], function () {
    Route::get('articles/json', 'SellingController@articlesJson');
});

Route::group(['prefix' => 'article'], function () {
    Route::get('{id}/transaction', 'ArticleController@transaction')->name('article.transaction');
    Route::get('{id}/settings', 'ArticleController@showSetting')->name('article.setting.index');
});

Route::group(['prefix' => 'warehouse'], function () {
    Route::get('{id}/supply', 'WarehouseController@supplyIndex')->name('warehouse.supply.inner');
    Route::post('{id}/supply', 'SupplyController@warehouseStore')->name('warehouse.supply.store');

    Route::get('{id}/transaction', 'WarehouseController@transaction')->name('warehouse.transaction');
    Route::get('{id}/settings', 'WarehouseController@showSetting')->name('warehouse.setting.index');
});

Route::group(['prefix' => 'sellpoint'], function () {
    Route::get('{id}/supply', 'SellpointController@supplyIndex')->name('sellpoint.supply.inner');
    Route::post('{id}/supply', 'SupplyController@sellpointStore')->name('sellpoint.supply.store');

    Route::get('{id}/transaction', 'SellpointController@transaction')->name('sellpoint.transaction');

    Route::get('{id}/settings', 'SellpointController@showSetting')->name('sellpoint.setting.index');

    Route::get('/json/{id}', 'SellpointController@warehouseJson')->name('sellpoint.warehouse.get');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('edit/profil/{id}', 'HomeController@edit')->name('profil');
Route::get('settings/{id}', 'HomeController@setting')->name('setting');

resources/views/owners/warehouses/show/index.blade.php
@extends('owners.warehouses.show')
@section('show-content')
    <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex justify-content-center align-content-start flex-column">
            <h4>{{ $warehouse->name }}</h4>
            <h6>Localité : {{ $warehouse->location }}</h6>
            <h6>Capacité initial : {{ $warehouse->capacity }} articles</h6>
            <h6>Crée {{ $warehouse->created_at->diffForHumans() }}</h6>
        </div>
        <img src="{{ asset('img/warehouse.jpg') }}" class="img-fluid d-block" width="200px" alt="">
    </div>
    <hr class="w-100">
    <div class="row">
        <div class="col-xl-6">
            <div class="">
                <h6>Stockage</h6>
            </div>
            <div class="pd-b-30">
                <div id="chartPie" data-used="{{ $used }}" data-no-used="{{ $warehouse->capacity - $used }}" class="ht-300 ht-sm-300"></div>
            </div>
        </div>
        <div class="col-xl-6">
            <div class="">
                <h6>Articles</h6>
            </div>
            <div class="pd-b-30">
                <div id="chartPieContent" data-articles="{{ json_encode($articles) }}" class="ht-300 ht-sm-300"></div>
            </div>
        </div>
    </div><!-- row -->

@endsection

resources/views/owners/warehouses/show/setting.blade.php
@extends('owners.warehouses.show')

@section('show-content')
    <div id="modaldemo5" class="modal fade" style="display: none;" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content tx-size-sm">
                <div class="modal-body tx-center pd-y-20 pd-x-20">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <i class="icon icon ion-ios-close-outline tx-100 tx-danger lh-1 mg-t-20 d-inline-block"></i>
                    <h4 class="tx-danger  tx-semibold mg-b-20">Danger: suppression de l'entrepot !</h4>
                    <p class="mg-b-20 mg-x-20">Si vous etes sure de supprimer cet entrepot entrer <strong>{{ $warehouseSlug }}</strong></p>
                    <form action="{{ route('warehouse.destroy', $warehouse->id) }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <div class="form-group">
                            <input name="slugDelete" class="form-control is-warning tx-center" placeholder="" type="text" autofocus>
                        </div>
                        <button type="submit" class="btn btn-danger tx-11 tx-uppercase pd-y-12 pd-x-25 tx-mont tx-medium mg-b-20">
                            Supprimer</button>
                    </form>
                </div><!-- modal-body -->
            </div><!-- modal-content -->
        </div><!-- modal-dialog -->
    </div>

    <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex justify-content-center align-content-start flex-column">
            <h4><i class="ion-android-settings"></i> Paramètres {{ $warehouse->name }}</h4>
            <h6>Localité : {{ $warehouse->location }}</h6>
            <h6>Crée {{ $warehouse->created_at->diffForHumans() }}</h6>
        </div>
        <img src="{{ asset('img/warehouse.jpg') }}" class="img-fluid d-block" width="100px" alt="">
    </div>
    <hr class="w-100">
    <div class="d-flex align-content-center justify-content-between mt-4">
        <a href="{{ route('warehouse.edit', $warehouse->id) }}" style="cursor:pointer; color: #fff" class="btn btn-primary btn-with-icon">
            <div class="ht-40 justify-content-between">
                <span class="pd-x-15">EDITER L'ENTREPOT</span>
                <span class="icon wd-40"><i class="fa fa-edit"></i></span>
            </div>
        </a>
        <button style="cursor:pointer;" data-toggle="modal" data-target="#modaldemo5" class="btn btn-danger btn-with-icon">
            <div class="ht-40">
                <span class="icon wd-40"><i class="fa fa-trash-o"></i></span>
                <span class="pd-x-15">SUPPRIMER L'ENTREPOT</span>
            </div>
        </button>
    </div>
@endsection

resources/views/owners/warehouses/show/supply.blade.php
@extends('owners.warehouses.show')

@section('show-content')
    <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex justify-content-center align-content-start flex-column">
            <h4>Ajouter des articles à {{ $warehouse->name }}</h4>
            <h5>Stockage libre: {{ ($warehouse->capacity - $used) }}</h5>
            <h5>Stockage utilise: {{ $used ?? 0 }}</h5>
        </div>
        <img src="{{ asset('img/warehouse.jpg') }}" class="img-fluid d-block" width="100px" alt="">
    </div>
    <hr class="w-100">
    <div class="d-flex align-content-center">
        <form action="{{ route('warehouse.supply.store', $warehouse->id) }}" class="w-100" method="POST">
            @csrf
            <div class="col-lg-12 mg-t-10-force w-100 d-flex flex-column justify-content-center align-items-center">
                <div class="row col-lg-12 mg-t-10-force w-100">
                    <div class="form-group has-success col-6">
                        <select name="article_id" class="form-control select2-show-search" data-placeholder="Choisir l'article">
                            @if($articles)
                                @foreach($articles as $article)
                                    <option value="{{ $article->id }}">{{ $article->name }} ({{ $article->caracts }} {{ $article->price }}XOF)</option>
                                @endforeach
                            @endif
                        </select>
                    </div>
                    <div class="col-6 form-group">
                        <div class="col-lg has-success">
                            <input name="quantity" class="form-control tx-uppercase tx-center" placeholder="Entrer la quantité de l'article" type="number">
                        </div>
                    </div>
                    </div>
                <div class="form-group col-5 mt-3">
                    <button type="submit" style="cursor: pointer" class="btn btn-outline-primary bd-2 btn-oblong btn-block mg-b-10">AJOUTER L'ARTICLE A L'ENTREPOT</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/owners/warehouses/show/transaction.blade.php
@extends('owners.warehouses.show')

@section('show-content')
    <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex justify-content-center align-content-start flex-column">
            <h4>Aliomentation effectué sur {{ $warehouse->name }}</h4>
        </div>
        <img src="{{ asset('img/warehouse.jpg') }}" class="img-fluid d-block" width="80px" alt="">
    </div>
    <hr class="w-100">
    <div class="table-wrapper">
        <table id="datatable1" class="table display responsive nowrap">
            <thead>
            <tr>
                <th class="wd-5p tx-center">#</th>
                <th class="wd-35p">Libéle de l'entrepot</th>
                <th class="wd-35p">Localité de l'entrepot</th>
                <th class="wd-10p">Capacité</th>
                <th class="wd-15p tx-center">Action</th>
            </tr>
            </thead>
            <tbody>
            @if(!empty($warehouses))
                @foreach($warehouses as $warehouse)
                    <tr>
                        <td class="text-center">{{ $warehouse->id }}</td>
                        <td>{{ $warehouse->name }}</td>
                        <td>{{ $warehouse->location }}</td>
                        <td class="text-center">{{ $warehouse->capacity }}</td>
                        <td class="tx-center">
                            <a href="{{ route('warehouse.show', $warehouse->id) }}"><button class="btn btn-outline-success mr-2 pd-t-2-force pd-b-2-force" style="cursor: pointer">VOIR</button></a>
                            <a href="{{ route('warehouse.edit', $warehouse->id) }}"><button class="btn btn-outline-info ml-2 pd-t-2-force pd-b-2-force" style="cursor: pointer">EDITER</button></a>
                        </td>
                    </tr>
                @endforeach
            @else
                <tr class="odd">
                    <td colspan="4" class="dataTables_empty" valign="top">
                        Aucun entrepot n'a été enregitré
                    </td>
                </tr>
            @endif
            </tbody>
        </table>
    </div>
@endsection