routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect()->route('login');
});

Route::resource('warehouse', WarehouseController::class);
Route::resource('sellpoint', SellpointController::class);
Route::resource('article', ArticleController::class);
Route::resource('employe', EmployeController::class);
Route::resource('selling', SellingController::class);
Route::resource('messagerie', MessagerieController::class);

Route::group(['prefix' => 'selling'], function () {
    Route::get('articles/json', 'SellingController@articlesJson');
});

Route::group(['prefix' => 'article'], function () {
    Route::get('{id}/transaction', 'ArticleController@transaction')->name('article.transaction');
    Route::get('{id}/settings', 'ArticleController@showSetting')->name('article.setting.index');
});

Route::group(['prefix' => 'warehouse'], function () {
    Route::get('{id}/supply', 'WarehouseController@supplyIndex')->name('warehouse.supply.inner');
    Route::post('{id}/supply', 'SupplyController@warehouseStore')->name('warehouse.supply.store');

    Route::get('{id}/transaction', 'WarehouseController@transaction')->name('warehouse.transaction');
    Route::get('{id}/settings', 'WarehouseController@showSetting')->name('warehouse.setting.index');
});

Route::group(['prefix' => 'sellpoint'], function () {
    Route::get('{id}/supply', 'SellpointController@supplyIndex')->name('sellpoint.supply.inner');
    Route::post('{id}/supply', 'SupplyController@sellpointStore')->name('sellpoint.supply.store');

    Route::get('{id}/transaction', 'SellpointController@transaction')->name('sellpoint.transaction');

    Route::get('{id}/settings', 'SellpointController@showSetting')->name('sellpoint.setting.index');

    Route::get('/json/{id}', 'SellpointController@warehouseJson')->name('sellpoint.warehouse.get');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('edit/profil/{id}', 'HomeController@edit')->name('profil');
Route::get('settings/{id}', 'HomeController@setting')->name('setting');

app/Employe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Permission\Traits\HasRoles;

class Employe extends Model
{
    use HasRoles;

    public function __construct()
    {
        $this->table = 'users';
    }

    public static function all($columns = ['*'])
    {
        return self::query()
            ->where('level', '=', 0)
            ->get(
                is_array($columns) ? $columns : func_get_args()
            );
    }

    protected $fillable = [
        'name', 'lastname', 'contact', 'level', 'picture', 'username', 'email', 'password',
    ];

    protected $guard_name = 'web';

    public function sellpoint()
    {
        return $this->belongsTo(Sellpoint::class);
    }

    public function sellings()
    {
        return $this->hasMany(Selling::class, 'user_id');
    }

}

app/Http/Controllers/EmployeController.php
<?php

namespace App\Http\Controllers;

use App\Employe;
use App\Rules\OldPassword;
use App\Sellpoint;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class EmployeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    private function adminCheck()
    {
        if(!Auth::user()->hasRole('admin')) {
           abort(403);
        }
    }

    private function valid(array $data, $withImage = true, $profil = false, $changePassword = false, $model = null, $accountSets = false){

        $messages = [
            'required' => 'Ce champs est requis.',
            'min' => 'Un minimun de :min caractères est requis pour ce champs.',
            'regex' => 'Mauvais format du champs',
            'image' => 'Charger une image',
            'mimes' => 'Charger l\'image dans un format jpg,jpeg ou png',
            'max' => 'La taille de l\'image ne doit pas depasser 1Mo',
            'numeric' => 'Ce champs doit contenir uniquement des chiffes',
            'unique' => 'Cet e-mail est déjà utilisé',
            'email' => 'Entrer une bonne adresse email',
            'confirmed' => 'Le mot de passe n\'a pas ete confirmer',
            'same' => 'Les mot de passe sont diffenrents',
        ];

        if ($profil) {

            return Validator::make($data, [
                'name' => 'required|regex:/^[a-z][a-z0-9 \-]+/i|min:3',
                'lastname' => 'required|regex:/^[a-z][a-z0-9 \-]+/i|min:3',
                'contact' => 'required|regex:/^\([0-9]{3}\) [0-9]{2}(\-[0-9]{3}){2}/i',
                'picture' => $withImage ? 'image|mimes:jpg,jpeg,png|max:1000' : 'nullable',
            ], $messages);

        } elseif ($changePassword) {

            return Validator::make($data, [
                'old_pass' => ['required', new OldPassword($model)],
                'password' => 'required|confirmed|min:8',
                'password_confirmation' => 'required|same:password|min:8'
            ], $messages);

        } elseif ($accountSets) {

            $messages = [
                'unique' => 'La valeur de ce champs est déjà utilisé',
                'required' => 'Ce champs est requis.',
                'min' => 'Un minimun de :min caractères est requis pour ce champs.',
                'regex' => 'Mauvais format du champs',
            ];

            return Validator::make($data, [
                'email' => ($data['email']) ? 'email|unique:users' : 'nullable',
                'username' => ($data['username']) ? 'regex:/^[a-z][a-z0-9 \-]+/i|min:3|unique:users' : 'nullable',
            ], $messages);

        } else {

            return Validator::make($data, [
                'name' => 'required|regex:/^[a-z][a-z ]+/i|min:3',
                'lastname' => 'required|regex:/^[a-z][a-z ]+/i|min:3',
                'sex' => 'required',
                'contact' => 'required|regex:/^\([0-9]{3}\) [0-9]{2}(\-[0-9]{3}){2}/i',
                'role' => 'required',
                'email' => 'required|email|unique:users',
                'picture' => $withImage ? 'image|mimes:jpg,jpeg,png|max:1000' : 'nullable',
                'sellpoint_id' => 'required|numeric'
            ], $messages);

        }

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->adminCheck();
        $employes = User::where('level', '=', 0)->get();
        return view('owners.employes.all', compact('employes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->adminCheck();
        $sellpoints = Sellpoint::all();
        return view('owners.employes.create', compact('sellpoints'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $this->adminCheck();
        $existImage = $request->file('picture') ? true : false;

        $validator = $this->valid($request->all(), $existImage);

        if ($validator->fails()) {
            return redirect()
                ->route('employe.create')
                ->withErrors($validator)
                ->withInput();
        }

        $parts = explode('@', $request->get('email'));
        $username = $parts[0];
        $uValid = Validator::make(['username' => $username], ['username' => 'alpha_num|unique:users',]);
        $i = 0;
        while ($uValid->fails()) {
            $username = $username . $i;
            $uValid = Validator::make(['username' => $username], ['username' => 'alpha_num|unique:users',]);
            $i++;
        }

        if ($existImage) {
            $path = $request->file('picture')->store('public/img/profil/'.$username);
        }

        $employe = new Employe();

        $employe->name = ucwords($request->get('name'));
        $employe->lastname = ucwords($request->get('lastname'));
        $employe->sex = $request->get('sex');
        $employe->contact = $request->get('contact');
        $employe->email = $request->get('email');
        $employe->username = $username;
        $employe->picture = $existImage ? $path : null;
        $employe->password = Hash::make('stockgestion');

        if ($request->get('role') !== 'admin') {
            $sellpoint = Sellpoint::find($request->get('sellpoint_id'));
            $employe->sellpoint()->associate($sellpoint);
        } else {
            $employe->level = 1;
        }

        $employe->save();

        $user = User::find($employe->id);

        $user->assignRole($request->get('role'));

        if ($request->get('role') === 'admin') {
            $role = ($user->sex === 'Masculin') ? 'L\'administrateur' : 'L\'administratrice';
        } elseif ($request->get('role') === 'manager') {
            $role = 'Le manager de';
        } else {
            $role = ($user->sex === 'Masculin') ? 'Le vendeur' : 'La vendeuse';
        }

        return redirect()->route('employe.create')->with(['success' => true, 'name' => $employe->name, 'lastname' => $employe->lastname, 'email' => $employe->email, 'password' => 'stockgestion', 'role' => $role]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function show($id)
    {
        $month = Carbon::now()->locale('fr_FR')->format('F');

        $user = User::findOrFail($id);
        $roles = $user->getRoleNames()->first();

        $employe = Employe::find($id);
        $sellpoint = $employe->sellpoint;
        $admin = $sellpoint->admin;
        $sellpoints = $admin->sellpoints;

        $nbreEmploye = 0;
        $nbreArticle = 0;
        $soldeMensuel = 0;

        foreach ($sellpoint->users as $emp) {
            ++$nbreEmploye;
        }

        foreach ($sellpoint->articles as $art) {
            $nbreArticle += $art->pivot->quantity;
        }

        foreach ($sellpoint->sellings as $selling) {
            if($selling->created_at->format('F') === $month) {
                $soldeMensuel += $selling->quantity * $selling->article->price;
            }
        }

        $userSlug = $admin->username . '/' . $sellpoint->id . '/' . $user->username;

        if ($roles === 'manager') {
            $role = 'Manager de stock';
        }
        elseif ($roles === 'seller') {
            $role = ($user->sex === 'Masculin') ? 'Vendeur' : 'Vendeuse';
        }

        $color = [
            'bg-purple',
            'bg-info',
            'bg-br-primary',
            'bg-warning',
            'bg-indigo',
            'bg-teal',
            'bg-pink',
            'bg-orange',
        ];
        $i = rand(0, 7);
        $bgcolor = $color[$i];

        return view('owners.employes.show.index', compact('user', 'role', 'sellpoint', 'sellpoints', 'userSlug', 'bgcolor', 'nbreEmploye', 'nbreArticle', 'soldeMensuel' ));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        if ($request->get('change_role') === 'on') {

            $user = User::findOrFail($id);

            if ($request->get('role') === 'manager') {
                $role = $request->get('role');
            }
            elseif ($request->get('role') === 'seller') {
                $role = ($user->sex === 'Masculin') ? 'vendeur' : 'vendeuse';
            }

            if ($user->getRoleNames()->first() !== $request->get('role')) {
                $old_role = $user->getRoleNames()->first();
                $new_role = $request->get('role');

                $user->removeRole($old_role);
                $user->assignRole($new_role);

                return redirect()->route('employe.show', $user->id)->with(['change_role' => true, 'role' => $role]);
            }

            return redirect()->route('employe.show', $user->id)->with(['no_change_role' => false, 'role' => $role]);

        }

//        if ($request->get('change_sellpoint') === 'on') {
//
//            $user = User::findOrFail($id);
//            if ($user->sellpoint->id === $request->get('change_sellpoint')) {
//

resources/views/owners/employes/show/index.blade.php
@extends('owners.employes.show')
@section('show-content')
    <div id="modaldemo5" class="modal fade" style="display: none;" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content tx-size-sm">
                <div class="modal-body tx-center pd-y-20 pd-x-20">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <i class="icon icon ion-ios-close-outline tx-100 tx-danger lh-1 mg-t-20 d-inline-block"></i>
                    <h4 class="tx-danger tx-semibold mg-b-20">Danger: suppression de l'employe !</h4>
                    <p class="mg-b-20 mg-x-20">Si vous etes sure de supprimer cet employe entrer <br><strong>{{ $userSlug ?? '' }}</strong></p>
                    <form action="{{ route('employe.destroy', $user->id) }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <div class="form-group">
                            <input name="slugDelete" class="form-control is-warning tx-center" placeholder="" type="text" autofocus>
                        </div>
                        <button type="submit" class="btn btn-danger tx-11 tx-uppercase pd-y-12 pd-x-25 tx-mont tx-medium mg-b-20">Supprimer</button>
                    </form>
                </div><!-- modal-body -->
            </div><!-- modal-content -->
        </div><!-- modal-dialog -->
    </div>
   {{-- <div id="modaldemo6" class="modal fade" style="display: none;" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content tx-size-sm">
                <div class="modal-body tx-center pd-y-20 pd-x-20">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <i class="icon icon fa fa-shopping-cart tx-100 tx-primary lh-1 mg-t-20 d-inline-block"></i>
                    <h4 class="tx-primary tx-semibold mg-b-20">Modifiaction !</h4>
                    <p class="mg-b-20 mg-x-20">Changer le point de vente de <strong>{{ $user->lastname }} {{ $user->name }}</strong></p>
                    <form action="{{ route('employe.update', $user->id) }}" method="POST">
                        @method('PUT')
                        <input type="hidden" name="change_sellpoint" value="on">
                        @csrf
                        <div style="width: 400px;" class="form-group bd-info col-12">
                            <select class="form-control select2 col-12" data-placeholder="Choose Browser">
                                @foreach($sellpoints as $sell)
                                    <option value="{{ $sell->id }}">{{ $sell->name }} ( {{ $sell->location }} )</option>
                                @endforeach
                            </select>
                        </div><!-- form-group -->
                        <button type="submit" class="btn btn-primary tx-11 tx-uppercase pd-y-12 pd-x-25 tx-mont tx-medium mg-b-20">Modifier</button>
                    </form>
                </div><!-- modal-body -->
            </div><!-- modal-content -->
        </div><!-- modal-dialog -->
    </div>--}}
    <div id="modaldemo4" class="modal fade" style="display: none;" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content tx-size-sm">
                <div class="modal-body tx-center pd-y-20 pd-x-20">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <i class="icon icon ion-key tx-100 tx-info lh-1 mg-t-20 d-inline-block"></i>
                    <h4 class="tx-info tx-semibold mg-b-20">Modifiaction !</h4>
                    <p class="mg-b-20 mg-x-20">Changer la fonction de <strong>{{ $user->lastname }} {{ $user->name }}</strong></p>
                    <form action="{{ route('employe.update', $user->id) }}" method="POST">
                        @method('PUT')
                        <input type="hidden" name="change_role" value="on">
                        @csrf
                        <div style="width: 400px;" class="form-group bd-info col-12">
                            <select class="form-control select2 col-12" name="role" data-placeholder="Choisir le role">
                                <option value="manager">Manager de stock</option>
                                <option value="seller">{{ ($user->sex === 'Masculin') ? 'Vendeur' : 'Vendeuse' }}</option>
                            </select>
                        </div><!-- form-group -->
                        <button type="submit" class="btn btn-info tx-11 tx-uppercase pd-y-12 pd-x-25 tx-mont tx-medium mg-b-20">Modifier</button>
                    </form>
                </div><!-- modal-body -->
            </div><!-- modal-content -->
        </div><!-- modal-dialog -->
    </div>
    <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex justify-content-center align-content-start flex-column">
            <h3>{{ $user->lastname }} {{ $user->name }}</h3>
            <h6>{{ $user->sex }}</h6>
            <h6>{{ $role }} au point de vente {{ $sellpoint->name }}, {{ $sellpoint->location }}</h6>
            <h6>{{ $user->email }}</h6>
            <h6>{{ $user->contact }}</h6>
            @php
                $picture = str_replace('public', 'storage', $user->picture);
            @endphp
        </div>
        <img id="profil_img" src="{{ asset($picture) }}" class="img-fluid d-block" width="200px" alt="">
    </div>

    <hr class="w-100">
    <h6 class="tx-uppercase mg-b-20-force">Informations sur le ponit de vente {{ $sellpoint->name }}, {{ $sellpoint->location }}</h6>
    <div class="col-sm-10 col-xl-8 m-auto">
        <div class="{{ $bgcolor }} rounded overflow-hidden">
            <div class="pd-x-20 pd-t-20 d-flex align-items-center justify-content-between">
                <div class="d-flex align-items-center">
                    <div class="mg-l-20 text-center">
                        <p class="tx-20 tx-white tx-lato tx-bold mg-b-10 lh-1">Artisan(s)</p>
                        <p class="tx-18 tx-spacing-1 tx-mont tx-semibold tx-uppercase tx-white-8">{{ $nbreEmploye }}</p>
                        <p class="tx-11 tx-spacing-1 tx-uppercase tx-white-8">Actif</p>
                    </div>
                </div>
                <div class="text-center">
                    <p class="tx-20 tx-white tx-lato tx-bold mg-b-10 lh-1">Article(s)</p>
                    <p class="tx-18 tx-spacing-1 tx-mont tx-semibold tx-uppercase tx-white-8">{{ $nbreArticle }}</p>
                    <p class="tx-11 tx-spacing-1 tx-uppercase tx-white-8">En stock</p>
                </div>
                <div class="text-center">
                    <p class="tx-20 tx-white tx-lato tx-bold mg-b-10 lh-1">Ventes</p>
                    <p class="tx-18 tx-spacing-1 tx-mont tx-semibold tx-uppercase tx-white-8">{{ $soldeMensuel }} CFA</p>
                    <p class="tx-11 tx-spacing-1 tx-uppercase tx-white-8">Dans ce mois</p>
                </div>
                <div class="d-flex justify-content-end align-items-center">
                    <a onmouseover="style.color = '#fff'" href="{{ route('sellpoint.show', $sellpoint->id) }}" style="cursor: pointer" class="btn tx-12 tx-white tx-lato bd-white-3 {{ $bgcolor }} tx-uppercase">Visiter</a>
                </div>
            </div>
            <div id="ch1" class="ht-30 tr-y-1"></div>
        </div>
    </div><!-- col-3 -->

    <hr class="w-100">
    <h6 class="tx-uppercase mg-b-20-force">Actions sur l'employe</h6>
    <div class="d-flex align-content-center justify-content-between">
        <button style="cursor:pointer;" data-toggle="modal" data-target="#modaldemo4" class="btn btn-info btn-with-icon">
            <div class="ht-40">
                <span class="icon wd-40"><i class="ion-android-settings"></i></span>
                <span class="pd-x-15">CHANGER LA FONCTION DE L'EMPLOYE</span>
            </div>
        </button>
        {{--<button style="cursor:pointer;" data-toggle="modal" data-target="#modaldemo6" class="btn btn-primary btn-with-icon">
            <div class="ht-40">
                <span class="icon wd-40"><i class="ion-android-settings"></i></span>
                <span class="pd-x-15">CHANGER LE POINT DE VENTE DE L'EMPLOYE</span>
            </div>
        </button>--}}
        <button style="cursor:pointer;" data-toggle="modal" data-target="#modaldemo5" class="btn btn-danger btn-with-icon">
            <div class="ht-40">
                <span class="icon wd-40"><i class="fa fa-trash-o"></i></span>
                <span class="pd-x-15">SUPPRIMER L'EMPLOYE</span>
            </div>
        </button>
    </div>
@endsection
@section('min-child-js')
    <script>
        (function () {
            let img = document.querySelector('#profil_img'),
                testImg = new Image();
            testImg.onerror = () => {
                img.src = location.origin + '/img/img11.jpg'
            }
            testImg.src = img.src
        })()
    </script>
@endsection