routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect()->route('login');
});

Route::resource('warehouse', WarehouseController::class);
Route::resource('sellpoint', SellpointController::class);
Route::resource('article', ArticleController::class);
Route::resource('employe', EmployeController::class);
Route::resource('selling', SellingController::class);
Route::resource('messagerie', MessagerieController::class);

Route::group(['prefix' => 'selling'], function () {
    Route::get('articles/json', 'SellingController@articlesJson');
});

Route::group(['prefix' => 'article'], function () {
    Route::get('{id}/transaction', 'ArticleController@transaction')->name('article.transaction');
    Route::get('{id}/settings', 'ArticleController@showSetting')->name('article.setting.index');
});

Route::group(['prefix' => 'warehouse'], function () {
    Route::get('{id}/supply', 'WarehouseController@supplyIndex')->name('warehouse.supply.inner');
    Route::post('{id}/supply', 'SupplyController@warehouseStore')->name('warehouse.supply.store');

    Route::get('{id}/transaction', 'WarehouseController@transaction')->name('warehouse.transaction');
    Route::get('{id}/settings', 'WarehouseController@showSetting')->name('warehouse.setting.index');
});

Route::group(['prefix' => 'sellpoint'], function () {
    Route::get('{id}/supply', 'SellpointController@supplyIndex')->name('sellpoint.supply.inner');
    Route::post('{id}/supply', 'SupplyController@sellpointStore')->name('sellpoint.supply.store');

    Route::get('{id}/transaction', 'SellpointController@transaction')->name('sellpoint.transaction');

    Route::get('{id}/settings', 'SellpointController@showSetting')->name('sellpoint.setting.index');

    Route::get('/json/{id}', 'SellpointController@warehouseJson')->name('sellpoint.warehouse.get');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('edit/profil/{id}', 'HomeController@edit')->name('profil');
Route::get('settings/{id}', 'HomeController@setting')->name('setting');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    public function admin()
    {
        return $this->belongsTo(Admin::class);
    }

    public function warehouses ()
    {
        return $this->belongsToMany(Warehouse::class)->withPivot('quantity')->withTimestamps();
    }

    public function sellpoints()
    {
        return $this->belongsToMany(Sellpoint::class)->withPivot('quantity')->withTimestamps();
    }

    public function sellings()
    {
        return $this->hasMany(Selling::class);
    }

    protected $fillable = [
        'code', 'name', 'caracts', 'img_url', 'price',
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Admin;
use App\Article;
use GuzzleHttp\Psr7\UploadedFile;
use Illuminate\Http\File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Symfony\Component\Console\Input\StringInput;

/**
 * Class ArticleController
 * @package App\Http\Controllers
 */
class ArticleController extends Controller
{
    /**
     * ArticleController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $articles = Article::all();
        return view('owners.articles.all', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('owners.articles.create');
    }

    private function slugDecompose (String $str)
    {
        $parts = explode('/', $str);
        $username = $parts[0];
        $name = ucwords(str_replace('-', ' ', $parts[1]));
        $id = $parts[2];

        return (object) [
            'username' => $username,
            'name' => $name,
            'id' => $id,
        ];
    }

    /**
     * @param array $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    private function valid(array $data, $whithDescribe = true, $withImage = true, $update = false){


        $messages = [
            'required' => 'Ce champs est requis.',
            'min' => 'Un minimun de :min caractères est requis pour ce champs.',
            'regex' => 'Mauvais format du champs',
            'size' => 'Le code doit faire exactement :size caractères',
            'image' => 'Charger une image',
            'mimes' => 'Charger l\'image dans un format jpg,jpeg ou png',
            'max' => 'La taille de l\'image ne doit pas depasser 1Mo',
            'numeric' => 'Ce champs doit contenir uniquement des chiffes',
            'unique' => 'Le code a déjà été utilisé pour un article',
            ''
        ];

        if($update) {
            return Validator::make($data, [
                'name' => 'required|regex:/^[a-z][a-z0-9 \-]+/i|min:3',
                'caracts' => $whithDescribe ? 'regex:/^[a-z][a-z0-9 \-,]+/i|min:3' : 'nullable',
                'img_url' => $withImage ? 'image|mimes:jpg,jpeg,png|max:1000' : 'nullable',
                'price' => 'required|numeric|min:1',
            ], $messages);
        }

        return Validator::make($data, [
            'name' => 'required|regex:/^[a-z][a-z0-9 \-]+/i|min:3',
            'caracts' => $whithDescribe ? 'regex:/^[a-z][a-z0-9 \-,]+/i|min:3' : 'nullable',
            'img_url' => $withImage ? 'image|mimes:jpg,jpeg,png|max:1000' : 'nullable',
            'price' => 'required|numeric|min:1',
            'code' => 'unique:App\Article,code|required|alpha_num|size:8|'
        ], $messages);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $existImage = $request->file('img_url') ? true : false;
        $existCaracts = $request->get('caracts') ? true : false;

        $validator = $this->valid($request->all(), $existCaracts, $existImage);

        if ($validator->fails()) {
            return redirect('article/create')
                ->withErrors($validator)
                ->withInput();
        }

        $admin = Admin::find(Auth::id());

        if ($existImage) {
            $path = $request->file('img_url')->store('public/img/articles/'.$admin->username);
        }


        $datas = [
            'name' => ucwords($request->get('name')),
            'code' => strtoupper($request->get('code')),
            'caracts' => $request->get('caracts'),
            'img_url' => $path ?? null,
            'price' => $request->get('price'),
        ];


        $article = Article::create($datas)->admin()->associate($admin);
        $article->save();
        return redirect()->route('article.create')->with(['success' => true]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article = Article::findOrFail($id);
        $warehouses = $article->warehouses;
        $sellpoints = $article->sellpoints;

        $articleSlug = $article->admin->username.'/'.Str::slug($article->name).'/'.$article->id;

        $bgcolor = [
            'bg-purple',
            'bg-info',
            'bg-br-primary',
            'bg-success',
            'bg-warning',
            'bg-danger',
            'bg-indigo',
            'bg-teal',
            'bg-pink',
            'bg-orange',
        ];

        return view('owners.articles.show.index', compact('article', 'warehouses', 'sellpoints', 'bgcolor', 'articleSlug'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $article = Article::findOrFail($id);
        return view('owners.articles.edit', compact('article'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        $article = Article::findOrFail($id);
        if(!empty($article)) {


            $existImage = $request->file('img_url') ? true : false;
            $existCaracts = $request->get('caracts') ? true : false;

            $validator = $this->valid($request->all(), $existCaracts, $existImage, true);

            if ($validator->fails()) {
                return redirect('article/'.$id.'/edit')
                    ->withErrors($validator)
                    ->withInput();
            }

            if ($article->name !== $request->get('name')) {
                $article->name = $request->get('name');
            }
            if($existImage) {
                Storage::delete($article->img_url);
                $username = $article->admin()->first()->username;
                $article->img_url = $request->file('img_url')->store('public/img/articles/'.$username);
            }
            if ($article->price !== $request->get('price')) {
                $article->price = $request->get('price');
            }
            if ($article->caracts !== $request->get('caracts')) {
                $article->caracts = $request->get('caracts');
            }

            $article->save();

            $nameChange = $article->wasChanged('name');
            $caractsChange = $article->wasChanged('caracts');
            $imgChange = $article->wasChanged('img_url');
            $priceChange = $article->wasChanged('price');


            return redirect()->route('article.edit', $id)->with([
                'name' => $nameChange,
                'caracts' => $caractsChange,
                'price' => $priceChange,
                'img' => $imgChange
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Request $request, $id)
    {
        $admin = Admin::findOrFail(Auth::id());
        $article = $admin->articles()->where('id', $id)->get()->toArray();


        if(!empty($article)) {

            $validator = Validator::make($request->all(), [
                'slugDelete' => 'required|regex:/^[a-z][a-z0-9\-]+\/[a-z0-9\-]+\/[0-9]+$/i|min:3',
            ]);


            if ($validator->fails()) {
                return redirect ( )->route('article.show', $id);
            }



            $article = (object) $article[0];
            $datas = $this->slugDecompose($request->get('slugDelete'));

            $name = ucwords(strtolower($article->name));

            if ($admin->username === $datas->username && $article->id == $datas->id && $name === $datas->name) {

                $admin->articles()->where('id', $id)->delete();
                return redirect()->route('article.index')->with(['success' => true, 'name' => $article->name]);

            }

            return redirect()->back();

        }
    }
}

resources/views/owners/articles/show/index.blade.php
@extends('owners.articles.show')
@section('show-content')
    <div id="modaldemo5" class="modal fade" style="display: none;" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content tx-size-sm">
                <div class="modal-body tx-center pd-y-20 pd-x-20">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <i class="icon icon ion-ios-close-outline tx-100 tx-danger lh-1 mg-t-20 d-inline-block"></i>
                    <h4 class="tx-danger  tx-semibold mg-b-20">Danger: suppression de l'article !</h4>
                    <p class="mg-b-20 mg-x-20">Si vous etes sure de supprimer cet article entrer <strong>{{ $articleSlug }}</strong></p>
                    <form action="{{ route('article.destroy', $article->id) }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <div class="form-group">
                            <input name="slugDelete" class="form-control is-warning tx-center" placeholder="" type="text" autofocus>
                        </div>
                        <button type="submit" class="btn btn-danger tx-11 tx-uppercase pd-y-12 pd-x-25 tx-mont tx-medium mg-b-20">Supprimer</button>
                    </form>
                </div><!-- modal-body -->
            </div><!-- modal-content -->
        </div><!-- modal-dialog -->
    </div>

    <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex justify-content-center align-content-start flex-column">
            <h4>{{ $article->name }}</h4>
            <h6 class="tx-14-force" style="max-width: 300px">{{ $article->caracts ?? 'Aucune description' }}</h6>
            <h6>Prix Unitaire : {{ $article->price }} XOF</h6>
            <h6>Crée {{ $article->created_at->diffForHumans() }}</h6>
            @php
                $img_url = str_replace('public', 'storage', $article->img_url);
                function getQuantity ($model)
                    {
                        $used = DB::table('article_warehouse')
                            ->select(DB::raw('sum(quantity) as total'))
                            ->where('warehouse_id', '=', $model->id)
                            ->get();

                        return $used[0]->total;
                    }
                    $sellId = 0;
                    $wareId = 0;
            @endphp
        </div>
        <img id="article_img" src="{{ asset($img_url) }}" class="img-fluid d-block" width="200px" alt="">
    </div>
    <hr class="w-100">
    <h6 class="tx-uppercase mg-b-10-force"> @if(!empty($warehouses->toArray())) Disponibilite dans les entrepots @else Cet article n'a ete atribuer a aucun entrepot @endif</h6>
    <div class="row row-sm">
        @if($warehouses)

            @foreach($warehouses as $warehouse)
                @php
                    $i = rand(0, 9);
                    $qty = ($warehouse->pivot->quantity * 100) / getQuantity($warehouse);
                @endphp
                <div class="col-sm-6 col-xl-4">
                    <div class="{{ $bgcolor[$i] }} rounded overflow-hidden">
                        <div class="pd-x-20 pd-t-20 d-flex align-items-center justify-content-between">
                            <div class="d-flex align-items-center">
                                <i class="ion ion-ios-filing-outline tx-60 lh-0 tx-white op-7"></i>
                                <div class="mg-l-20">
                                    <p class="tx-10 tx-spacing-1 tx-mont tx-semibold tx-uppercase tx-white-8 mg-b-10">{{ $warehouse->name }}</p>
                                    @if($warehouse->pivot->quantity !== 0)
                                        <p class="tx-24 tx-white tx-lato tx-bold mg-b-0 lh-1">{{ $warehouse->pivot->quantity }}</p>
                                    @else
                                        <p class="tx-18 tx-white tx-lato tx-bold mg-b-6-force lh-1">{{ 'En rupture de stock' }}</p>
                                    @endif
                                    <span class="tx-11 tx-roboto tx-white-8">{{ round($qty, 2) }}% du stock</span>
                                </div>
                            </div>
                            <div class="d-flex justify-content-end align-items-center">
                                <a onmouseover="style.color = '#fff'" href="{{ route('warehouse.show', $warehouse->id) }}" style="cursor: pointer" class="btn tx-12 tx-white tx-lato bd-white-3 {{ $bgcolor[$i] }} tx-uppercase">Visiter</a>
                            </div>
                        </div>
                        <div id="{{ 'warehouse'.++$wareId }}" class="ht-50 tr-y-1"></div>
                    </div>
                </div><!-- col-3 -->
            @endforeach

        @endif
    </div><!-- row -->

    <hr class="w-100">

    <h6 class="tx-uppercase mg-b-20-force">@if(!empty($sellpoints->toArray())) Disponibilite dans les points de ventes @else Cet article n'a ete atribuer a aucun point de vente @endif</h6>
    <div class="row row-sm">
        @if($sellpoints)

            @foreach($sellpoints as $sellpoint)
                @php
                    $i = rand(0, 9);
                @endphp
                <div class="col-sm-6 col-xl-4">
                    <div class="{{ $bgcolor[$i] }} rounded overflow-hidden">
                        <div class="pd-x-20 pd-t-20 d-flex align-items-center justify-content-between">
                            <div class="d-flex align-items-center">
                                <i class="ion ion-bag tx-60 lh-0 tx-white op-7"></i>
                                <div class="mg-l-20">
                                    <p class="tx-10 tx-spacing-1 tx-mont tx-semibold tx-uppercase tx-white-8 mg-b-10">{{ $sellpoint->name }}</p>
                                    @if($sellpoint->pivot->quantity !== 0)
                                        <p class="tx-24 tx-white tx-lato tx-bold mg-b-0 lh-1">{{ $sellpoint->pivot->quantity }}</p>
                                    @else
                                        <p class="tx-18 tx-white tx-lato tx-bold mg-b-6-force lh-1">{{ 'En rupture de stock' }}</p>
                                    @endif
                                    <span class="tx-11 tx-roboto tx-white-8"></span>
                                </div>
                            </div>
                            <div class="d-flex justify-content-end align-items-center">
                                <a onmouseover="style.color = '#fff'" href="{{ route('sellpoint.show', $sellpoint->id) }}" style="cursor: pointer" class="btn tx-12 tx-white tx-lato bd-white-3 {{ $bgcolor[$i] }} tx-uppercase">Visiter</a>
                            </div>
                        </div>
                        <div id="{{ 'sellpoint'.++$sellId }}" class="ht-50 tr-y-1"></div>
                    </div>
                </div><!-- col-3 -->
            @endforeach

        @endif
    </div><!-- row -->
    <div class="col-sm-6 col-xl-4 mg-t-20 mg-xl-t-0">
        <div class="bg-teal rounded overflow-hidden">

        </div>
    </div><!-- col-4 -->

    <hr class="w-100">

    <h6 class="tx-uppercase mg-b-20-force">Actions sur l'article</h6>
    <div class="d-flex align-content-center justify-content-between">
        <a href="{{ route('article.edit', $article->id) }}" style="cursor:pointer; color: #fff" class="btn btn-primary btn-with-icon">
            <div class="ht-40 justify-content-between">
                <span class="pd-x-15">EDITER L'ARTICLE</span>
                <span class="icon wd-40"><i class="fa fa-edit"></i></span>
            </div>
        </a>
        <button style="cursor:pointer;" data-toggle="modal" data-target="#modaldemo5" class="btn btn-danger btn-with-icon">
            <div class="ht-40">
                <span class="icon wd-40"><i class="fa fa-trash-o"></i></span>
                <span class="pd-x-15">SUPPRIMER L'ARTICLE</span>
            </div>
        </button>
    </div>
    <div id="counter" class="d-none" data-count-sellpoint="{{ count($sellpoints->toArray()) }}" data-count-warehouse="{{ count($warehouses->toArray()) }}"></div>
@endsection
@section('min-child-js')
    <script src="{{ asset('js/rickraw/article-sellpoint-load.js') }}"></script>
    <script>
        (function () {
            let img = document.querySelector('#article_img'),
                testImg = new Image();
            testImg.onerror = () => {
                img.src = location.origin + '/img/img11.jpg'
            }
            testImg.src = img.src
        })()
    </script>
@endsection