routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect()->route('login');
});

Route::resource('warehouse', WarehouseController::class);
Route::resource('sellpoint', SellpointController::class);
Route::resource('article', ArticleController::class);
Route::resource('employe', EmployeController::class);
Route::resource('selling', SellingController::class);
Route::resource('messagerie', MessagerieController::class);

Route::group(['prefix' => 'selling'], function () {
    Route::get('articles/json', 'SellingController@articlesJson');
});

Route::group(['prefix' => 'article'], function () {
    Route::get('{id}/transaction', 'ArticleController@transaction')->name('article.transaction');
    Route::get('{id}/settings', 'ArticleController@showSetting')->name('article.setting.index');
});

Route::group(['prefix' => 'warehouse'], function () {
    Route::get('{id}/supply', 'WarehouseController@supplyIndex')->name('warehouse.supply.inner');
    Route::post('{id}/supply', 'SupplyController@warehouseStore')->name('warehouse.supply.store');

    Route::get('{id}/transaction', 'WarehouseController@transaction')->name('warehouse.transaction');
    Route::get('{id}/settings', 'WarehouseController@showSetting')->name('warehouse.setting.index');
});

Route::group(['prefix' => 'sellpoint'], function () {
    Route::get('{id}/supply', 'SellpointController@supplyIndex')->name('sellpoint.supply.inner');
    Route::post('{id}/supply', 'SupplyController@sellpointStore')->name('sellpoint.supply.store');

    Route::get('{id}/transaction', 'SellpointController@transaction')->name('sellpoint.transaction');

    Route::get('{id}/settings', 'SellpointController@showSetting')->name('sellpoint.setting.index');

    Route::get('/json/{id}', 'SellpointController@warehouseJson')->name('sellpoint.warehouse.get');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('edit/profil/{id}', 'HomeController@edit')->name('profil');
Route::get('settings/{id}', 'HomeController@setting')->name('setting');

app/Sellpoint.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sellpoint extends Model
{
    public function admin()
    {
        return $this->belongsTo(Admin::class);
    }

    public function articles ()
    {
        return $this->belongsToMany(Article::class)->withPivot('quantity')->withTimestamps();
    }

    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function sellings()
    {
        return $this->hasMany(Selling::class);
    }

    protected $fillable = [
        'name', 'location'
    ];
}

app/Http/Controllers/SellpointController.php
<?php

namespace App\Http\Controllers;

use App\Admin;
use App\Article;
use App\Sellpoint;
use App\Warehouse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

/**
 * Class SellpointController
 * @package App\Http\Controllers
 */
class SellpointController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $sellpoints = Sellpoint::all();
        return view('owners.sellpoints.all', compact('sellpoints'));
    }

    /**
     * @param String $str
     * @return object
     */
    private function slugDecompose (String $str)
    {
        $parts = explode('/', $str);
        $username = $parts[0];
        $name = ucwords(str_replace('-', ' ', $parts[1]));
        $id = $parts[2];

        return (object) [
            'username' => $username,
            'name' => $name,
            'id' => $id,
        ];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('owners.sellpoints.create');
    }

    /**
     * @param $model
     * @return mixed
     */
    private function sum ($model)
    {
        $used = DB::table('article_sellpoint')
            ->select(DB::raw('sum(quantity) as total'))
            ->where('article_id', '=', $model->id)
            ->get();

        return $used[0]->total;
    }

    /**
     * @param array $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    private function valid(array $data){
        $messages = [
            'required'    => 'Ce champs est requis.',
            'min'    => 'Un minimun de :min est requis pour ce champs.',
            'regex' => 'Mauvais format du champs'
        ];

        return Validator::make($data, [
            'name' => 'required|regex:/^[a-z][a-z0-9 \-]+/i|min:3',
            'location' => 'required|regex:/^[a-z][a-z0-9 \-,]+/i|min:3',
        ], $messages);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $validator = $this->valid($request->all());

        if ($validator->fails()) {
            return redirect('sellpoint/create')
                ->withErrors($validator)
                ->withInput();
        }

        $admin = Admin::find(Auth::id());
        $sellpoint = Sellpoint::create($request->all())->admin()->associate($admin);
        $sellpoint->save();
        $success = true;
        return redirect()->route('sellpoint.create')->with(['success' => $success]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $sellpoint = Sellpoint::findOrFail($id);

        $articles = [];

        foreach ($sellpoint->articles as $article) {
            if ($article->pivot->quantity > 0) {
                $tmp = [
                    'name' => $article->name,
                    'value' => $article->pivot->quantity,
                ];

                array_push($articles, $tmp);
            }
        }

        if (empty($articles))
        {
            $articles = [
                0 => [
                    'name' => 'Vide',
                    'value' => 100,
                ]
            ];
        }

        return view('owners.sellpoints.show.index', compact('sellpoint', 'articles'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit($id)
    {
        $sellpoint = Sellpoint::findOrFail($id);
        return view('owners.sellpoints.edit', compact('sellpoint'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        $sellpoint = Sellpoint::findOrFail($id);
        if(!empty($sellpoint)) {
            $validator = $this->valid($request->all());

            if ($validator->fails()) {
                return redirect('warehouse/'.$id.'/edit')
                    ->withErrors($validator)
                    ->withInput();
            }

            if ($sellpoint->name !== $request->get('name')) {
                $sellpoint->name = $request->get('name');
            }
            if ($sellpoint->location !== $request->get('location')) {
                $sellpoint->location = $request->get('location');
            }

            $sellpoint->save();

            $nameChange = $sellpoint->wasChanged('name');
            $localChange = $sellpoint->wasChanged('location');

            return redirect()->route('sellpoint.edit', $id)->with(['nameChange' => $nameChange, 'localChange' => $localChange]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $admin = Admin::findOrFail(1);
        $sellpoint = $admin->sellpoints()->where('id', $id)->get()->toArray();


        if(!empty($sellpoint)) {

            $validator = Validator::make($request->all(), [
                'slugDelete' => 'required|regex:/^[a-z][a-z0-9\-]+\/[a-z0-9\-]+\/[0-9]+$/i|min:3',
            ]);


            if ($validator->fails()) {
                return redirect('/warehouse/' . $id . '/settings');
            }


            $sellpoint = (object)$sellpoint[0];
            $datas = $this->slugDecompose($request->get('slugDelete'));

            $name = ucwords(strtolower($sellpoint->name));

            if ($admin->username === $datas->username && $sellpoint->id == $datas->id && $name === $datas->name) {
                $admin->sellpoints()->where('id', $id)->delete();

                return redirect()->route('warehouse.index')->with(['success' => true, 'name' => $sellpoint->name]);
            }

            return redirect('/sellpoint/' . $id . '/settings');
        }
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function supplyIndex ($id)
    {
        $warehouses = Warehouse::select('id','name')->get();
        $sellpoint = Sellpoint::findOrFail($id);
        return view('owners.sellpoints.show.supply', compact('sellpoint', 'warehouses'));
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function transaction ($id)
    {
        $sellpoint = Sellpoint::findOrFail($id);
        return view('owners.sellpoints.show.transaction', compact('sellpoint'));
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function showSetting ($id)
    {
        $sellpoint = Sellpoint::findOrFail($id);
        $sellpointSlug = Str::slug($sellpoint->name);
        $username = $sellpoint->admin()->first()->username;
        $sellpointSlug = $username . '/' . $sellpointSlug . '/' . $sellpoint->id;
        return view('owners.sellpoints.show.setting', compact('sellpoint', 'sellpointSlug'));
    }

    /**
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function warehouseJson ($id)
    {

        $warehouse = Warehouse::findOrFail($id);

        $articles = [];

        foreach ($warehouse->articles as $article) {

            if ($article->pivot->quantity > 0) {
                $tmp = [
                    'id' => $article->id,
                    'name' => $article->name,
                    'value' => $article->pivot->quantity,
                ];

                array_push($articles, $tmp);
            }

        }

        return response()->json($articles);

    }

}

resources/views/owners/sellpoints/all.blade.php
@extends('layouts.swup')
@section('content')
    <div id="app-warehouse-show">
        <div class="br-mainpanel">
            <div class="br-pagetitle d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                    <i class="icon ion-ios-filing-outline"></i>
                    <div class="ml-3">
                        <h4>Liste des point de vente disponible</h4>
                    </div>
                </div>
            </div>

            <div class="br-pagebody pd-t-15-force pd-b-15-force">
                <div class="br-section-wrapper">
                    <div class="table-wrapper">
                        <table id="datatable1" class="table display responsive nowrap">
                            <thead>
                            <tr>
                                <th class="wd-5p tx-center">#</th>
                                <th class="wd-35p">Libéle du point de vente</th>
                                <th class="wd-35p">Localité du point de vente</th>
                                <th class="wd-15p tx-center">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(!empty($sellpoints))
                                @foreach($sellpoints as $sellpoint)
                                    <tr>
                                        <td class="text-center">{{ $sellpoint->id }}</td>
                                        <td>{{ $sellpoint->name }}</td>
                                        <td>{{ $sellpoint->location }}</td>
                                        <td class="tx-center">
                                            <a href="{{ route('sellpoint.show', $sellpoint->id) }}"><button class="btn btn-outline-success mr-2 pd-t-2-force pd-b-2-force" style="cursor: pointer">VOIR</button></a>
                                            <a href="{{ route('sellpoint.edit', $sellpoint->id) }}"><button class="btn btn-outline-info ml-2 pd-t-2-force pd-b-2-force" style="cursor: pointer">EDITER</button></a>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr class="odd">
                                    <td colspan="4" class="dataTables_empty" valign="top">
                                        Aucun point de vente n'a été enregitré
                                    </td>
                                </tr>
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('child-js')
    <script>
        $('#datatable1').DataTable({
            responsive: true,
            lengthMenu: [5],
            language: {
                searchPlaceholder: 'Recherche...',
                sSearch: '',
                lengthMenu: '_MENU_ points de vente par page',
            }
        });
    </script>
@endsection

resources/views/owners/sellpoints/create.blade.php
@extends('layouts.swup')
@section('content')
    <div id="app-sellpoint-edit">
        <div class="br-mainpanel">
            <div class="br-pagetitle d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                    <i class="icon ion-ios-filing-outline"></i>
                    <div class="ml-3">
                        <h4>Creer un nouveau point de vente</h4>
                    </div>
                </div>
                @if(session()->get('success'))
                    <div class="col-xl-5" id="successNotify">
                        <div class="alert alert-success alert-solid" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                            <div class="d-flex align-items-center justify-content-start">
                                <i style="color: #fff" class="icon ion-ios-checkmark alert-icon tx-32 mg-t-5 mg-xs-t-0"></i>
                                <span><strong>Succès !</strong> Le point de vente</span>
                            </div><!-- d-flex -->
                        </div>
                    </div>
                @endif
            </div>

            <div class="br-pagebody">
                <div class="br-section-wrapper">
                    <form action="{{ route('sellpoint.store') }}" method="POST">
                        @csrf
                        <div class="form-layout form-layout-2">
                            <div class="row no-gutters">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label">Libélé du point de vente: <span class="tx-danger">*</span></label>
                                        <input class="form-control" type="text" name="name" value="{{ old('name') }}" placeholder="Entrer le libélé du point de vente">
                                        @error('name')
                                            <ul class="parsley-errors-list filled" id="parsley-id-26">
                                                <li class="parsley-required">{{ $message }}</li>
                                            </ul>
                                        @enderror
                                    </div>
                                </div><!-- col-4 -->

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label">Localité du point de vente: <span class="tx-danger">*</span></label>
                                        <input class="form-control" type="text" name="location" value="{{ old('location') }}" placeholder="Entrer la localité du point de vente">
                                        @error('location')
                                            <ul class="parsley-errors-list filled" id="parsley-id-26">
                                                <li class="parsley-required">{{ $message }}</li>
                                            </ul>
                                        @enderror
                                    </div>
                                </div><!-- col-4 -->
                            </div><!-- row -->
                            <div class="d-flex justify-content-between form-layout-footer bd pd-20 bd-t-0">
                                <div>
                                    <button class="btn btn-info">Creer</button>
                                    <button type="reset" class="btn btn-secondary">Effacer</button>
                                </div>
                                <div>
                                    <a href="{{ route('sellpoint.index') }}"><button type="button" class="btn btn-outline-success">Voir mes point de vente</button></a>
                                </div>
                            </div><!-- form-group -->
                        </div><!-- form-layout -->
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/owners/sellpoints/edit.blade.php
@extends('layouts.swup')
@section('content')
    <div id="app-warehouse-edit">
        <div class="br-mainpanel">
            <div class="br-pagetitle d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                    <i class="icon ion-ios-filing-outline"></i>
                    <div class="ml-3">
                        <h4>Edition de {{ $sellpoint->name }}</h4>
                    </div>
                </div>
            </div>
            <div class="br-pagebody">
                <div class="br-section-wrapper">
                    <form action="{{ route('sellpoint.update', $sellpoint->id) }}" method="POST">
                        @method('PUT')
                        @csrf
                        <div class="form-layout form-layout-2">
                            <div class="row no-gutters">

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label">Libélé du point de vente: <span class="tx-danger">*</span></label>
                                        <input class="form-control" type="text" name="name" value="{{ old('name')??$sellpoint->name }}" placeholder="Entrer le libélé du point de vente">
                                        @error('name')
                                        <ul class="parsley-errors-list filled" id="parsley-id-26">
                                            <li class="parsley-required">{{ $message }}</li>
                                        </ul>
                                        @enderror
                                        @if(session()->get( 'nameChange' ))
                                            <ul class="parsley-errors-list filled" id="parsley-id-26">
                                                <li style="color: #23BF08 !important;" class="parsley-required">Le libélé a été modifié avec succès</li>
                                            </ul>
                                        @endif
                                    </div>
                                </div><!-- col-4 -->

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="form-control-label">Localité du point de vente: <span class="tx-danger">*</span></label>
                                        <input class="form-control" type="text" name="location" value="{{ old('location')??$sellpoint->location }}" placeholder="Entrer la localité du point de vente">
                                        @error('location')
                                        <ul class="parsley-errors-list filled" id="parsley-id-26">
                                            <li class="parsley-required">{{ $message }}</li>
                                        </ul>
                                        @enderror
                                        @if(session()->get( 'localChange' ))
                                            <ul class="parsley-errors-list filled" id="parsley-id-26">
                                                <li style="color: #23BF08 !important;" class="parsley-required">La localité a été modifiée avec succès</li>
                                            </ul>
                                        @endif
                                    </div>
                                </div><!-- col-4 -->

                            </div><!-- row -->
                            <div class="d-flex justify-content-between form-layout-footer bd pd-20 bd-t-0">
                                <div>
                                    <button class="btn btn-info">Mettre à jour</button>
                                </div>
                                <div>
                                    @if(route('sellpoint.setting.index', $sellpoint->id) === redirect()->back()->getTargetUrl() | session()->exists('url'))
                                        @php
                                            if (!session()->exists('url')) {
                                                request()->session()->put('url', redirect()->back()->getTargetUrl());
                                            }
                                        @endphp
                                        <a href="{{ session()->get('url') }}"><button type="button" class="btn btn-outline-primary">Retour</button></a>
                                    @else
                                        <a href="{{ route('sellpoint.index') }}"><button type="button" class="btn btn-outline-success">Voir mes points de ventes</button></a>
                                    @endif
                                </div>
                            </div><!-- form-group -->
                        </div><!-- form-layout -->
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('child-js')

@endsection

resources/views/owners/sellpoints/show.blade.php
@extends('layouts.swup')
@section('content')

    <div id="app-sellpoint-edit">
        <div class="br-mainpanel">
            <div class="br-pagetitle d-flex justify-content-center align-items-center">
                <div class="pd-10 bd rounded mg-t-10">
                    <ul class="nav nav-pills flex-column flex-md-row justify-content-end" role="tablist">
                        <li class="nav-item"><a class="nav-link {{ preg_match_all('/^\/sellpoint\/[0-9]+$/i', request()->getRequestUri()) ? 'active' : '' }}"  href="{{ route('sellpoint.show', $sellpoint->id) }}"><i class="ion-ios-home"></i> Presentation</a></li>
                        <li class="nav-item"><a class="nav-link {{ strpos(request()->getRequestUri(), 'supply')  ? 'active' : '' }}"  href="{{ route('sellpoint.supply.inner', $sellpoint->id) }}"><i class=""></i> Alimentation</a></li>
                        <li class="nav-item"><a class="nav-link {{ strpos(request()->getRequestUri(), 'transaction')  ? 'active' : '' }}"  href="{{ route('sellpoint.transaction', $sellpoint->id) }}"><i class="fa fa-stack-exchange"></i> Transaction</a></li>
                        <li class="nav-item"><a class="nav-link {{ strpos(request()->getRequestUri(), 'settings')  ? 'active' : '' }}" href="{{ route('sellpoint.setting.index', $sellpoint->id) }}"><i class="ion-android-settings"></i> Paramètres</a></li>
                    </ul>
                </div>
                @if(session()->get('success'))
                    <div class="col-xl-5" id="successNotify">
                        <div class="alert alert-success alert-solid" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                            <div class="d-flex align-items-center justify-content-start">
                                <i style="color: #fff" class="icon ion-ios-checkmark alert-icon tx-22 mg-t-5 mg-xs-t-0"></i>
                                <span><strong>Succès !</strong> L'article a été ajouté</span>
                            </div><!-- d-flex -->
                        </div>
                    </div>
                @endif
                @if(session()->get('failed'))
                    <div class="col-xl-5" id="successNotify">
                        <div class="alert alert-danger alert-solid" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                            <div class="d-flex align-items-center justify-content-start">
                                <i style="color: #fff" class="icon ion-ios-checkmark alert-icon tx-22 mg-t-5 mg-xs-t-0"></i>
                                <span><strong>Désole !</strong> Il n'y que {{ session()->get('artQuantity') }}  {{ session()->get('artName') }} dans l'entrepot {{ session()->get('warName') }}</span>
                            </div><!-- d-flex -->
                        </div>
                    </div>
                @endif
            </div>
            <div class="br-pagebody ">
                <div class="br-section-wrapper">

                    @yield('show-content')

                </div>
            </div>
        </div>
    </div>

@endsection
@section('child-js')
    <script src="{{ asset('js/charts/sellpoint.show.content.js') }}"></script>
    @yield('myChild-js')
@endsection